name: mvp_package_ui
description: "MVP Job Portal UI (Flutter) — light blue theme, 108job-style UX"
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  go_router: ^16.2.1
  google_fonts: ^6.2.1
  intl: ^0.20.2
  appwrite: ^18.0.0

  flutter_localizations:
    sdk: flutter
  http: ^1.5.0
  file_picker: ^10.3.2
  url_launcher: ^6.3.2
  share_plus: ^12.0.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: "^0.13.1" # Added this line

# Add dependencies for bin scripts
executables:
  appwrite: ^18.0.0

flutter_launcher_icons: # Added this block
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/iconband.png"
  min_sdk_android: 21 # set min_sdk_android to 21 or higher

flutter:
  uses-material-design: true
  assets:
    - assets/mock_jobs.json
    - assets/mock_chats.json
    - assets/mock_profile.json
    - assets/images/