import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:google_fonts/google_fonts.dart';

// Language enum
enum AppLanguage {
  lao,
  english,
}

// Language state
class LanguageState {
  final AppLanguage language;
  final Locale locale;
  final String languageCode;

  LanguageState({
    required this.language,
    required this.locale,
    required this.languageCode,
  });

  LanguageState copyWith({
    AppLanguage? language,
    Locale? locale,
    String? languageCode,
  }) {
    return LanguageState(
      language: language ?? this.language,
      locale: locale ?? this.locale,
      languageCode: languageCode ?? this.languageCode,
    );
  }
}

// Language provider
final languageProvider = StateProvider<LanguageState>((ref) {
  return LanguageState(
    language: AppLanguage.lao,
    locale: const Locale('lo'),
    languageCode: 'lo',
  );
});

// Function to switch language
void switchLanguage(WidgetRef ref, AppLanguage language) {
  final languageState = ref.read(languageProvider);
  
  switch (language) {
    case AppLanguage.lao:
      ref.read(languageProvider.notifier).state = languageState.copyWith(
        language: AppLanguage.lao,
        locale: const Locale('lo'),
        languageCode: 'lo',
      );
      break;
    case AppLanguage.english:
      ref.read(languageProvider.notifier).state = languageState.copyWith(
        language: AppLanguage.english,
        locale: const Locale('en'),
        languageCode: 'en',
      );
      break;
  }
}

// Text translation service
class AppLocalizations {
  static final Map<String, Map<String, String>> _localizedStrings = {
    // Lao translations
    'lo': {
      'app_title': 'mvp package',
      'splash_title': 'MVP Package',
      'splash_subtitle': 'ແອັບຫາວຽກງານສຳລັບຄົນລາວ',
      'onboarding_title_1': 'ຄົ້ນຫາວຽກງານ',
      'onboarding_desc_1': 'ຊອກຫາວຽກງານທີ່ເໝາະສຳລັບທ່ານ ແລະ ສະໝັກໄດ້ທັນທີ',
      'onboarding_title_2': 'ແຊດກັບນາຍຈ້າງ',
      'onboarding_desc_2': 'ສົນທະນາກັບນາຍຈ້າງໂດຍກົງ ແລະ ຮັບຂໍ້ມູນກ່ຽວກັບບໍລິສັດ',
      'onboarding_title_3': 'ຈັດການໃບສະໝັກ',
      'onboarding_desc_3': 'ຕິດຕາມສະຖານະຂອງໃບສະໝັກງານຂອງທ່ານໄດ້ທຸກເວລາ',
      'skip': 'ຂ້າມ',
      'next': 'ຕໍ່ໄປ',
      'get_started': 'ເລີ່ມຕົ້ນໃຊ້ງານ',
      'login': 'ເຂົ້າສູ່ລະບົບ',
      'welcome_back': 'ຍິນດີຕ້ອນຮັບກັບ',
      'login_to_continue': 'ເຂົ້າສູ່ລະບົບເພື່ອສືບຕໍ່',
      'or_continue_with': 'ຫຼືສືບຕໍ່ດ້ວຍ',
      'email': 'ອີເມວ',
      'password': 'ລະຫັດຜ່ານ',
      'forgot_password': 'ລືມລະຫັດຜ່ານ?',
      'no_account': 'ຍັງບໍ່ມີບັນຊີ? ',
      'register_now': 'ສະໝັກສະມາຊິກ',
      'register': 'ສ້າງບັນຊີ',
      'register_subtitle': 'ເລິ່ມຕ້ອນໃຊ້ງານ mvp package',
      'have_account': 'ມີບັນຊີອີຢູ່ແລ້ວ? ',
      'login_now': 'ເຂົ້າສູ່ລະບົບ',
      'full_name': 'ຊື່-ນາມສະກຸນ',
      'confirm_password': 'ຢືນຢັນລະຫັດຜ່ານ',
      'job_seeker': 'ຜູ້ຫາວຽກງານ',
      'employer': 'ນາຍຈ້າງ',
      'jobs': 'ຫາວຽກງານ',
      'applied': 'ສະໝັກແລ້ວ',
      'chat': 'ແຊດ',
      'profile': 'ໂປຣໄຟລ໌',
      'post_job': 'ປະກາດງານ',
      'all_jobs': 'ງານທັ້ງໝົດ',
      'search_jobs': 'ຄົ້ນຫາວຽກງານ...',
      'filter': 'ກັອງ',
      'no_jobs_found': 'ບໍ່ພົບງານທີ່ຄ້ອນຫາ',
      'my_applications': 'ໃບສະໝັກຂອງຂ້ອຍ',
      'logout': 'ອອກຈາກລະບົບ',
      'logout_confirm': 'ທ່ານຕ້ອງການອອກຈາກລະບົບບໍ?',
      'cancel': 'ຍົກເລີກ',
      'ok': 'ຕົກລົງ',
      'edit_profile': 'ແກ້ໄຂໂປຣໄຟລ໌',
      'personal_info': 'ຂໍ້ມູນສ່ວນຕົວ',
      'phone': 'ເບີໂທລະສັບ',
      'province': 'ແຂວງ/ເມືອງ',
      'skills': 'ທັກສະ ແລະ ຄວາມສາມາດ',
      'about': 'ກ່ຽວກັບຕົນເອງ',
      'documents': 'ເອກະສານ ແລະ ເລຊູເມ',
      'no_chats': 'ຍັງບໍ່ມີການສົນທະນາ',
      'no_chats_desc': 'ເມື່ອທ່ານສະໝັກງານ ການສົນທະນາຈະປາກົດທີ່ນີ້',
      'find_jobs': 'ຫາວຽກງານທີ່ສົນໃຈ',
      'today': 'ມື້ນີ້',
      'yesterday': 'ມື້ວານ',
      'days_ago': 'ມື້ທີ່ແລ້ວ',
      'save': 'ບັນທຶກ',
      'delete': 'ລົບ',
      'apply': 'ສະໝັກ',
      'applied_success': 'ສະໝັກງານສຳເລັດ',
      'apply_job': 'ສະໝັກງານນີ້',
      'job_detail': 'ລາຍລະອຽດງານ',
      'company': 'ບໍລິສັດ',
      'salary': 'ເງິນເດືອນ',
      'location': 'ສະຖານທີ່',
      'job_type': 'ປະເພດງານ',
      'description': 'ລາຍລະອຽດ',
      'requirements': 'ຄວາມຕ້ອງການ',
      'benefits': 'ສິດຜົນ',
      'no_internet': 'ບໍ່ມີການເຊື່ອມຕໍ່ອິນເຕີເນັດ',
      'try_again': 'ລອງອີກຄັ້ງ',
      'error': 'ກເກີດຂໍ້ຜີດພາດ',
      'loading': 'ກຳລັງໂຫຼດ...', 
      'search': 'ຄົ້ນຫາ',
      'refresh': 'ຣີເຟຣດ',
      'mark_as_read': 'ທໍໂຄ່ງໜາຍວ່າອ່ານແລ້ວ',
      'mark_as_unread': 'ທໍໂຄ່ງໜາຍວ່າຍັງບໍ່ອ່ານ',
      'delete_chat': 'ລົບແຊດ',
      'delete_chat_confirm': 'ທ່ານຕ້ອງການລົບແຊດນີ້ບໍ?',
      'delete_application': 'ລົບໃບສະໝັກ',
      'delete_application_confirm': 'ທ່ານຕ້ອງການລົບໃບສະໝັກນີ້ບໍ?',
      'pending': 'ລໍຖ້າການພິຈາລະນາ',
      'reviewing': 'ກຳລັງພິຈາລະນາ',
      'interview': 'ການສັມພາດ',
      'accepted': 'ໄດ້ຮັບການຢອມຮັບ',
      'rejected': 'ຖືກປະຕິເສດ',
      'view_job': 'ດູງານ',
      'upload_resume': 'ອັບໂຫລດເລຊູເມ',
      'update_resume': 'ອັບເດດເລຊູເມ',
      'resume_uploaded': 'ມີໄຟລ໌ເລຊູເມແລ້ວ',
      'no_resume': 'ຍັງບໍ່ໄດ້ອັບໂຫລດເລຊູເມ',
      'feature_coming_soon': 'ຟີເຈີອັບໂຫລດໄຟລ໌ຈະຖືກເພີ່ມໃນເວີຊັນຕໍ່ໄປ',
      'all': 'ທັງໝົດ',
      'completed': 'ສຳເລັດ',
      'role': 'ບົດບາດ',
      'email_required': 'ກະລຸນາປ້ອນອີເມວ',
      'email_invalid': 'ຮູບແບບອີເມວບໍ່ຖືກຕ້ອງ',
      'password_required': 'ກະລຸນາປ້ອນລະຫັດຜ່ານ',
      'password_min_length': 'ລະຫັດຜ່ານຕ້ອງມີຢ່າງໜ້ອຍ 6 ໂຕອັກສອນ',
      'name_required': 'ກະລຸນາກໍລອກຊື່-ນາມສະກຸນ',
      'name_min_length': 'ຊື່ຕ້ອງມີຢ່າງໜ້ອຍ 2 ໂຕອັກສອນ',
      'confirm_password_required': 'ກະລຸນາຢືນຍັນລະຫັດຜ່ານ',
      'passwords_do_not_match': 'ລະຫັດຜ່ານບໍ່ຕຫົງກັນ',
      'password_min_length_hint': 'ຢ່າງໜ້ອຍ 6 ໂຕອັກສອນ',
      'demo_info': '💡 ສຳລັບທົດສອບ: ໃຊ້ອີເມວແລະລະຫັດຜ່ານໃດກໍ່ໄດ້',
      'demo_example': 'ຕົວຢ່າງ: test@example.com / 123456',
      'negotiable': 'ຕາມຕົກລົງ',
      'lao_currency': 'ລາວ',
      'saved': 'ບັນທຶກແລ້ວ!',
      'weeks_ago': 'ອາທິດທີ່ແລ້ວ',
      'months_ago': 'ເດືອນທີ່ແລ້ວ',
      'no_applications_yet': 'ຍັງບໍ່ມີໃບສະໝັກງານ',
      'no_applications_desc': 'ເມື່ອທ່ານສະໝັກງານ ໃບສະໝັກຈະປາກົດທີ່ນີ້',
      'no_applications_in_category': 'ບໍ່ມີໃບສະໝັກໃນໝວດນີ້',
      'applied_on': 'ສະໝັກເມື່ອ',
      'interview_on': 'ສັມພາດເມື່ອ',
      'application_details': 'ລາຍລະອຽດໃບສະໝັກ',
      'job_title': 'ຕໍາແໜ່ງງານ',
      'status': 'ສະຖານະ',
      'applied_date': 'ວັນທີສະໝັກ',
      'interview_date': 'ວັນທີສັມພາດ',
      'cover_letter': 'ຈົດໝາຍສະໝັກງານ',
      'application_deleted': 'ລົບໃບສະໝັກແລ້ວ',
      'search_chats_feature': 'ຄົ້ນຫາແຊດ',
      'error_loading_chats': 'ບໍ່ສາມາດໂຫຼດແຊດໄດ້',
      'start_conversation': 'ສົ່ງຂໍ້ຄວາມເພື່ອເລີ່ມການສົນທນາ',
      'chat_deleted': 'ລົບແຊດກັບ',
      'error_loading_messages': 'ບໍ່ສາມາດໂຫຼດຂໍ້ຄວາມໄດ້',
      'call_feature': 'ໂທລະສັບ',
      'attach_file': 'ແນບໄຟລ໌',
      'type_message': 'ພິມຂໍ້ຄວາມ...', 
      'typing': 'ກຳລັງພິມ...', 
      'online': 'ອອນໄລນ໌',
      'offline': 'ອອບໄລນ໌',
      'chat_info': 'ຂໍ້ມູນແຊດ',
      'block_user': 'ບລັອກຜູ້ໃຊ້',
      'report': 'ລາຍງານ',
      'report_sent': 'ລາຍງານຖືກສົ່ງແລ້ວ',
      'loading_partner': 'ກຳລັງໂຫຼດ...', 
      'chat_info_message': 'ຂໍ້ມູນແຊດ',
      'block_user_message': 'ບລັອກຜູ້ໃຊ້',
      'job_not_found_error': 'ບໍ່ພົບຂໍ້ມູນງານ',
      'default_cover_letter': 'ສະບາຍດີເຈົ້າ ຂ້ອຍສົນໃຈຕໍາແໜ່ງງານນີ້ຫຼາຍ ແລະ ມີຄວາມຫວັງວ່າຈະໄດ້ມີໂອກາດຮ່ວມງານກັບທີມຂອງທ່ານ',
      'application_submitted': 'ສົ່ງໃບສະໝັກແລ້ວ! ກວດສອບໃນແຖບໃບສະໝັກຂອງຂ້ອຍ',
      'job_not_found': 'ບໍ່ພົບງານ',
      'job_not_found_message': 'ບໍ່ພົບລາຍລະອຽດງານທີ່ຕ້ອງການ',
      'job_bookmarked': 'ບັນທຶກງານແລ້ວ',
      'job_bookmark_removed': 'ຍົກເລີກການບັນທຶກ',
      'share_job': 'ແບ່ງປັນງານ',
      'posted_on': 'ປະກາດເມື່ອ',
      'no_description': 'ບໍ່ມີລາຍລະອຽດເພີ່ມເຕີມ',
      'about_company': 'ກ່ຽວກັບບໍລິສັດ',
      'company_description': 'ບໍລິສັດຊັ້ນນໍາໃນອຸດສາຫະກໍາ ພ້ອມໂອກາດເຕີບໂຕ ແລະ ສະວັດດິການທີ່ດີ',
      'start_chat_with_hr': 'ເລີ່ມການສົນທະນາກັບ HR',
      'applying': 'ກຳລັງສົ່ງ...', 
      'clear_all': 'ລົບລ້າງທັງໝົດ',
      'select_province': 'ເລືອກແຂວງ/ເມືອງ',
      'select_job_type': 'ເລືອກປະເພດງານ',
      'salary_range': 'ຊ່ວງເງິນເດືອນ',
      'experience_level': 'ລະດັບປະສົບການ',
      'select_experience': 'ເລືອກລະດັບປະສົບການ',
      'sort_by': 'ຈັດລຽງຕາມ',
      'apply_filters': 'ນຳໃຊ້ຕົວກອງ',
      'no_experience': 'ໃໝ່/ບໍ່ມີປະສົບການ',
      'experience_1_2_years': '1-2 ປີ',
      'experience_3_5_years': '3-5 ປີ',
      'experience_5_plus_years': '5+ ປີ',
      'sort_latest': 'ຫຼ້າສຸດ',
      'sort_salary_high_low': 'ເງິນເດືອນ: ສູງ-ຕ່ຳ',
      'sort_salary_low_high': 'ເງິນເດືອນ: ຕ່ຳ-ສູງ',
      'sort_company_az': 'ບໍລິສັດ A-Z',
      'status_pending': 'ລໍຖ້າການພິຈາລະນາ',
      'status_reviewing': 'ກຳລັງພິຈາລະນາ',
      'status_interview': 'ນັດສັມພາດ',
      'status_accepted': 'ໄດ້ຮັບການຄັດເລືອກ',
      'status_rejected': 'ບໍ່ໄດ້ຮັບການຄັດເລືອກ',
      // Bookmark related
      'bookmarked_jobs': 'ງານທີ່ບັນທຶກໄວ້',
      'bookmark': 'ບັນທຶກ',
      'bookmarked': 'ບັນທຶກແລ້ວ',
      'add_bookmark': 'ບັນທຶກງານ',
      'remove_bookmark': 'ຍົກເລີກບັນທຶກ',
      'bookmark_removed': 'ຍົກເລີກການບັນທຶກແລ້ວ',
      'job_bookmarked': 'ບັນທຶກງານແລ້ວ',
      'no_bookmarks': 'ຍັງບໍ່ມີງານທີ່ບັນທຶກ',
      'no_bookmarks_desc': 'ງານທີ່ທ່ານບັນທຶກໄວ້ຈະປາກົດທີ່ນີ້',
      'bookmarked_on': 'ບັນທຶກເມື່ອ',
      'clear_all_bookmarks': 'ລົບງານທີ່ບັນທຶກທັງໝົດ',
      'clear_all_bookmarks_confirm': 'ທ່ານແນ່ໃຈບໍ່ວ່າຕ້ອງການລົບງານທີ່ບັນທຶກທັງໝົດ?',
      'undo': 'ຍົກເລີກ',
      'unknown_job': 'ບໍ່ທຮາບຕຳແໜ່ງ',
      'unknown_company': 'ບໍ່ທຮາບບໍລິສັດ',
      'unknown_location': 'ບໍ່ທຮາບສະຖານທີ່',
      // Notification related
      'notifications': 'ການແຈ້ງເຕືອນ',
      'new_notification': 'ການແຈ້ງເຕືອນໃໝ່',
      'mark_all_read': 'ທໍໂຄ່ງທັງໝົດວ່າອ່ານແລ້ວ',
      'clear_notifications': 'ລົບທັງໝົດ',
      'no_notifications': 'ບໍ່ມີການແຈ້ງເຕືອນ',
      'no_notifications_desc': 'ການແຈ້ງເຕືອນກ່ຽວກັບງານຈະປາກົດທີ່ນີ້',
      // Company related
      'company_profile': 'ໂປຣໄຟລ໌ບໍລິສັດ',
      'about_company': 'ກ່ຽວກັບບໍລິສັດ',
      'company_jobs': 'ງານຂອງບໍລິສັດນີ້',
      'company_reviews': 'ບົດຄິດເຫັນ',
      'company_benefits': 'ສິດຜົນ',
      'company_culture': 'ວັດທະນະທໍາບໍລິສັດ',
      'employees_count': 'ຈໍານວນພະນັກງານ',
      'founded_year': 'ປີທີ່ກໍ່ຕັ້ງ',
      'company_rating': 'ຄະແນນບໍລິສັດ',
      'write_review': 'ຂຽນບົດຄິດເຫັນ',
      'read_reviews': 'ອ່ານບົດຄິດເຫັນ',
      // Review related
      'reviews': 'ບົດຄິດເຫັນ',
      'rating': 'ຄະແນນ',
      'review_title': 'ຫົວຂໍ້ບົດຄິດເຫັນ',
      'review_content': 'ເນື້ອໃນບົດຄິດເຫັນ',
      'pros': 'ຈຸດດີ',
      'cons': 'ຈຸດທີ່ຄວນປັບປຸງ',
      'current_employee': 'ພະນັກງານປັດຈຸບັນ',
      'former_employee': 'ອະດີດພະນັກງານ',
      'helpful': 'ມີປະໂຫຍດ',
      'not_helpful': 'ບໍ່ມີປະໂຫຍດ',
      'verified_review': 'ບົດຄິດເຫັນທີ່ຢືນຢັນແລ້ວ',
      // CV Builder related
      'cv_builder': 'ສ້າງ CV',
      'create_cv': 'ສ້າງ CV ໃໝ່',
      'edit_cv': 'ແກ້ໄຂ CV',
      'cv_templates': 'ແບບຟອມ CV',
      'personal_information': 'ຂໍ້ມູນສ່ວນຕົວ',
      'work_experience': 'ປະສົບການການງານ',
      'education': 'ການສຶກສາ',
      'skills': 'ທັກສະ',
      'projects': 'ໂປຣເຈັກ',
      'certifications': 'ໃບຢັ້ງຢືນ',
      'export_pdf': 'ສົ່ງອອກ PDF',
      'export_word': 'ສົ່ງອອກ Word',
      'preview_cv': 'ເບິ່ງຕົວຢ່າງ CV',
      'save_cv': 'ບັນທຶກ CV',
      // Analytics related
      'analytics': 'ສະຖິຕິ',
      'dashboard': 'ແດສບອດ',
      'statistics': 'ສະຖິຕິ',
      'profile_views': 'ການເບິ່ງໂປຣໄຟລ໌',
      'applications_sent': 'ໃບສະໝັກທີ່ສົ່ງ',
      'messages_received': 'ຂໍ້ຄວາມທີ່ໄດ້ຮັບ',
      'success_rate': 'ອັດຕາຄວາມສຳເລັດ',
      'job_categories': 'ປະເພດງານ',
      'salary_trends': 'ແນວໂນ້ມເງິນເດືອນ',
      // Interview related
      'interviews': 'ການສັມພາດ',
      'schedule_interview': 'ນັດເວລາສັມພາດ',
      'interview_date': 'ວັນທີ່ສັມພາດ',
      'interview_time': 'ເວລາສັມພາດ',
      'interview_type': 'ປະເພດການສັມພາດ',
      'video_call': 'ວິດິໂອໂທ',
      'phone_call': 'ໂທລະສັບ',
      'in_person': 'ພົບໜ້າ',
      'interview_location': 'ສະຖານທີ່ສັມພາດ',
      'meeting_url': 'ລິ້ງການປະຊຸມ',
      'interview_notes': 'ບັນທຶກ',
      'interview_preparation': 'ການກະກຽມ',
      'upcoming_interviews': 'ການສັມພາດທີ່ຈະມາເຖິງ',
      'interview_scheduled': 'ນັດແລ້ວ',
      'interview_confirmed': 'ຢືນຢັນແລ້ວ',
      'interview_completed': 'ສຳເລັດແລ້ວ',
      'interview_cancelled': 'ຍົກເລີກແລ້ວ',
      'interview_rescheduled': 'ເລື່ອນເວລາແລ້ວ',
    },
    // English translations
    'en': {
      'app_title': 'mvp package',
      'splash_title': 'MVP Package',
      'splash_subtitle': 'Job app for Lao people',
      'onboarding_title_1': 'Find Jobs',
      'onboarding_desc_1': 'Search for jobs that suit you and apply instantly',
      'onboarding_title_2': 'Chat with Employers',
      'onboarding_desc_2': 'Communicate directly with employers and get company information',
      'onboarding_title_3': 'Manage Applications',
      'onboarding_desc_3': 'Track the status of your job applications anytime',
      'skip': 'Skip',
      'next': 'Next',
      'get_started': 'Get Started',
      'login': 'Login',
      'email': 'Email',
      'password': 'Password',
      'forgot_password': 'Forgot Password?',
      'no_account': 'Don\'t have an account? ',
      'register_now': 'Register',
      'register': 'Create Account',
      'register_subtitle': 'Get started with mvp package',
      'have_account': 'Already have an account? ',
      'login_now': 'Login',
      'full_name': 'Full Name',
      'confirm_password': 'Confirm Password',
      'job_seeker': 'Job Seeker',
      'employer': 'Employer',
      'jobs': 'Jobs',
      'applied': 'Applied',
      'chat': 'Chat',
      'profile': 'Profile',
      'post_job': 'Post Job',
      'all_jobs': 'All Jobs',
      'search_jobs': 'Search jobs...', 
      'filter': 'Filter',
      'no_jobs_found': 'No jobs found',
      'my_applications': 'My Applications',
      'logout': 'Logout',
      'logout_confirm': 'Do you want to logout?',
      'cancel': 'Cancel',
      'ok': 'OK',
      'edit_profile': 'Edit Profile',
      'personal_info': 'Personal Information',
      'phone': 'Phone',
      'province': 'Province/City',
      'skills': 'Skills & Abilities',
      'about': 'About Me',
      'documents': 'Documents & Resume',
      'no_chats': 'No Conversations',
      'no_chats_desc': 'When you apply for jobs, conversations will appear here',
      'find_jobs': 'Find Jobs',
      'today': 'Today',
      'yesterday': 'Yesterday',
      'days_ago': 'days ago',
      'save': 'Save',
      'delete': 'Delete',
      'apply': 'Apply',
      'applied_success': 'Application Successful',
      'apply_job': 'Apply for this job',
      'job_detail': 'Job Detail',
      'company': 'Company',
      'salary': 'Salary',
      'location': 'Location',
      'job_type': 'Job Type',
      'description': 'Description',
      'requirements': 'Requirements',
      'benefits': 'Benefits',
      'no_internet': 'No Internet Connection',
      'try_again': 'Try Again',
      'error': 'Error',
      'loading': 'Loading...', 
      'search': 'Search',
      'refresh': 'Refresh',
      'mark_as_read': 'Mark as Read',
      'mark_as_unread': 'Mark as Unread',
      'delete_chat': 'Delete Chat',
      'delete_chat_confirm': 'Do you want to delete this chat?',
      'delete_application': 'Delete Application',
      'delete_application_confirm': 'Do you want to delete this application?',
      'pending': 'Pending',
      'reviewing': 'Reviewing',
      'interview': 'Interview',
      'accepted': 'Accepted',
      'rejected': 'Rejected',
      'view_job': 'View Job',
      'upload_resume': 'Upload Resume',
      'update_resume': 'Update Resume',
      'resume_uploaded': 'Resume Uploaded',
      'no_resume': 'No Resume Uploaded',
      'feature_coming_soon': 'File upload feature will be added in the next version',
      'all': 'All',
      'completed': 'Completed',
      'role': 'Role',
      'email_required': 'Please enter your email',
      'email_invalid': 'Invalid email format',
      'password_required': 'Please enter your password',
      'password_min_length': 'Password must be at least 6 characters',
      'name_required': 'Please enter your full name',
      'name_min_length': 'Name must be at least 2 characters',
      'confirm_password_required': 'Please confirm your password',
      'passwords_do_not_match': 'Passwords do not match',
      'password_min_length_hint': 'At least 6 characters',
      'demo_info': '💡 For testing: Use any email and password',
      'demo_example': 'Example: test@example.com / 123456',
      'negotiable': 'Negotiable',
      'lao_currency': 'Lao',
      'saved': 'Saved!',
      'weeks_ago': 'weeks ago',
      'months_ago': 'months ago',
      'no_applications_yet': 'No job applications yet',
      'no_applications_desc': 'When you apply for jobs, applications will appear here',
      'no_applications_in_category': 'No applications in this category',
      'applied_on': 'Applied on',
      'interview_on': 'Interview on',
      'application_details': 'Application Details',
      'job_title': 'Job Title',
      'status': 'Status',
      'applied_date': 'Applied Date',
      'interview_date': 'Interview Date',
      'cover_letter': 'Cover Letter',
      'application_deleted': 'Application deleted',
      'search_chats_feature': 'Search chats',
      'error_loading_chats': 'Unable to load chats',
      'start_conversation': 'Send a message to start the conversation',
      'chat_deleted': 'Deleted chat with',
      'error_loading_messages': 'Unable to load messages',
      'call_feature': 'Call',
      'attach_file': 'Attach file',
      'type_message': 'Type a message...', 
      'typing': 'Typing...', 
      'online': 'Online',
      'offline': 'Offline',
      'chat_info': 'Chat Info',
      'block_user': 'Block User',
      'report': 'Report',
      'report_sent': 'Report sent',
      'loading_partner': 'Loading...', 
      'chat_info_message': 'Chat information',
      'block_user_message': 'User blocked',
      'job_not_found_error': 'Job data not found',
      'default_cover_letter': 'Hello, I am very interested in this position and hope to have the opportunity to work with your team',
      'application_submitted': 'Application submitted! Check in my applications tab',
      'job_not_found': 'Job Not Found',
      'job_not_found_message': 'Job details not found',
      'job_bookmarked': 'Job bookmarked',
      'job_bookmark_removed': 'Bookmark removed',
      'share_job': 'Share job',
      'posted_on': 'Posted on',
      'no_description': 'No additional details',
      'about_company': 'About Company',
      'company_description': 'Leading company in the industry, with growth opportunities and good benefits',
      'start_chat_with_hr': 'Start conversation with HR',
      'applying': 'Applying...', 
      'clear_all': 'Clear All',
      'select_province': 'Select Province/City',
      'select_job_type': 'Select Job Type',
      'salary_range': 'Salary Range',
      'experience_level': 'Experience Level',
      'select_experience': 'Select Experience Level',
      'sort_by': 'Sort By',
      'apply_filters': 'Apply Filters',
      'no_experience': 'New/No Experience',
      'experience_1_2_years': '1-2 years',
      'experience_3_5_years': '3-5 years',
      'experience_5_plus_years': '5+ years',
      'sort_latest': 'Latest',
      'sort_salary_high_low': 'Salary: High-Low',
      'sort_salary_low_high': 'Salary: Low-High',
      'sort_company_az': 'Company A-Z',
      'status_pending': 'Pending',
      'status_reviewing': 'Reviewing',
      'status_interview': 'Interview',
      'status_accepted': 'Accepted',
      'status_rejected': 'Rejected',
      // Bookmark related
      'bookmarked_jobs': 'Bookmarked Jobs',
      'bookmark': 'Bookmark',
      'bookmarked': 'Bookmarked',
      'add_bookmark': 'Add Bookmark',
      'remove_bookmark': 'Remove Bookmark',
      'bookmark_removed': 'Bookmark Removed',
      'job_bookmarked': 'Job Bookmarked',
      'no_bookmarks': 'No Bookmarks Yet',
      'no_bookmarks_desc': 'Jobs you bookmark will appear here for easy access',
      'bookmarked_on': 'Bookmarked on',
      'clear_all_bookmarks': 'Clear All Bookmarks',
      'clear_all_bookmarks_confirm': 'Are you sure you want to remove all bookmarks?',
      'undo': 'Undo',
      'unknown_job': 'Unknown Job',
      'unknown_company': 'Unknown Company',
      'unknown_location': 'Unknown Location',
      // Notification related
      'notifications': 'Notifications',
      'new_notification': 'New Notification',
      'mark_all_read': 'Mark All Read',
      'clear_notifications': 'Clear All',
      'no_notifications': 'No Notifications',
      'no_notifications_desc': 'You\'ll receive notifications about job updates here',
      // Company related
      'company_profile': 'Company Profile',
      'about_company': 'About Company',
      'company_jobs': 'Jobs at this Company',
      'company_reviews': 'Reviews',
      'company_benefits': 'Benefits',
      'company_culture': 'Company Culture',
      'employees_count': 'Employees',
      'founded_year': 'Founded',
      'company_rating': 'Company Rating',
      'write_review': 'Write Review',
      'read_reviews': 'Read Reviews',
      // Review related
      'reviews': 'Reviews',
      'write_review': 'Write Review',
      'rating': 'Rating',
      'review_title': 'Review Title',
      'review_content': 'Review Content',
      'pros': 'Pros',
      'cons': 'Cons',
      'current_employee': 'Current Employee',
      'former_employee': 'Former Employee',
      'helpful': 'Helpful',
      'not_helpful': 'Not Helpful',
      'verified_review': 'Verified Review',
      // CV Builder related
      'cv_builder': 'CV Builder',
      'create_cv': 'Create CV',
      'edit_cv': 'Edit CV',
      'cv_templates': 'CV Templates',
      'personal_information': 'Personal Information',
      'work_experience': 'Work Experience',
      'education': 'Education',
      'skills': 'Skills',
      'projects': 'Projects',
      'certifications': 'Certifications',
      'export_pdf': 'Export PDF',
      'export_word': 'Export Word',
      'preview_cv': 'Preview CV',
      'save_cv': 'Save CV',
      // Analytics related
      'analytics': 'Analytics',
      'dashboard': 'Dashboard',
      'statistics': 'Statistics',
      'profile_views': 'Profile Views',
      'applications_sent': 'Applications Sent',
      'messages_received': 'Messages Received',
      'success_rate': 'Success Rate',
      'job_categories': 'Job Categories',
      'salary_trends': 'Salary Trends',
      // Interview related
      'interviews': 'Interviews',
      'schedule_interview': 'Schedule Interview',
      'interview_date': 'Interview Date',
      'interview_time': 'Interview Time',
      'interview_type': 'Interview Type',
      'video_call': 'Video Call',
      'phone_call': 'Phone Call',
      'in_person': 'In Person',
      'interview_location': 'Location',
      'meeting_url': 'Meeting URL',
      'interview_notes': 'Notes',
      'interview_preparation': 'Preparation',
      'upcoming_interviews': 'Upcoming Interviews',
      'interview_scheduled': 'Scheduled',
      'interview_confirmed': 'Confirmed',
      'interview_completed': 'Completed',
      'interview_cancelled': 'Cancelled',
      'interview_rescheduled': 'Rescheduled',
    }
  };

  static String translate(String key, String languageCode) {
    final translations = _localizedStrings[languageCode];
    if (translations == null) return key;
    return translations[key] ?? key;
  }

  static String of(BuildContext context, String key) {
    // In a real implementation, we would get the language code from the context
    // For now, we'll default to Lao
    return translate(key, 'lo');
  }
}
