import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:google_fonts/google_fonts.dart';

// Language enum
enum AppLanguage {
  lao,
  english,
}

// Language state
class LanguageState {
  final AppLanguage language;
  final Locale locale;
  final String languageCode;

  LanguageState({
    required this.language,
    required this.locale,
    required this.languageCode,
  });

  LanguageState copyWith({
    AppLanguage? language,
    Locale? locale,
    String? languageCode,
  }) {
    return LanguageState(
      language: language ?? this.language,
      locale: locale ?? this.locale,
      languageCode: languageCode ?? this.languageCode,
    );
  }
}

// Language provider
final languageProvider = StateProvider<LanguageState>((ref) {
  return LanguageState(
    language: AppLanguage.lao,
    locale: const Locale('lo'),
    languageCode: 'lo',
  );
});

// Function to switch language
void switchLanguage(WidgetRef ref, AppLanguage language) {
  final languageState = ref.read(languageProvider);
  
  switch (language) {
    case AppLanguage.lao:
      ref.read(languageProvider.notifier).state = languageState.copyWith(
        language: AppLanguage.lao,
        locale: const Locale('lo'),
        languageCode: 'lo',
      );
      break;
    case AppLanguage.english:
      ref.read(languageProvider.notifier).state = languageState.copyWith(
        language: AppLanguage.english,
        locale: const Locale('en'),
        languageCode: 'en',
      );
      break;
  }
}

// Text translation service
class AppLocalizations {
  static final Map<String, Map<String, String>> _localizedStrings = {
    // English translations
    'en': {
      'app_title': 'MVP Package',
      'splash_title': 'MVP Package',
      'splash_subtitle': 'The job app for Lao people',
      'onboarding_title_1': 'Discover Jobs',
      'onboarding_desc_1': 'Find jobs that suit you and apply instantly.',
      'onboarding_title_2': 'Chat with Employers',
      'onboarding_desc_2': 'Chat directly with employers and get company insights.',
      'onboarding_title_3': 'Manage Applications',
      'onboarding_desc_3': 'Track the status of your job applications anytime.',
      'skip': 'Skip',
      'next': 'Next',
      'get_started': 'Get Started',
      'login': 'Login',
      'welcome_back': 'MVP Jobs',
      'login_to_continue': 'Login to continue',
      'or_continue_with': 'Or continue with',
      'email': 'Email',
      'password': 'Password',
      'forgot_password': 'Forgot Password?',
      'no_account': 'Don\'t have an account? ',
      'register_now': 'Register',
      'remember_me': 'Remember Me',
      'register': 'Register',
      'register_subtitle': 'Get started with MVP Package',
      'have_account': 'Already have an account? ',
      'login_now': 'Login',
      'full_name': 'Full Name',
      'confirm_password': 'Confirm Password',
      'job_seeker': 'Job Seeker',
      'employer': 'Employer',
      'jobs': 'Jobs',
      'applied': 'Applied',
      'chat': 'Chat',
      'profile': 'Profile',
      'post_job': 'Post Job',
      'all_jobs': 'All Jobs',
      'search_jobs': 'Search for jobs...',
      'filter': 'Filter',
      'no_jobs_found': 'No jobs found',
      'my_applications': 'My Applications',
      'logout': 'Logout',
      'logout_confirm': 'Are you sure you want to logout?',
      'cancel': 'Cancel',
      'ok': 'OK',
      'edit_profile': 'Edit Profile',
      'tap_to_change_profile_picture': 'Tap to change profile picture',
      'personal_info': 'Personal Information',
      'phone': 'Phone',
      'province': 'Province',
      'skills': 'Skills',
      'about': 'About',
      'documents': 'Documents & Resume',
      'no_chats': 'No Chats Yet',
      'no_chats_desc': 'When you apply for a job, your conversations will appear here.',
      'find_jobs': 'Find Interesting Jobs',
      'today': 'Today',
      'yesterday': 'Yesterday',
      'days_ago': 'days ago',
      'save': 'Save',
      'delete': 'Delete',
      'apply': 'Apply',
      'applied_success': 'Applied successfully',
      'apply_job': 'Apply for this Job',
      'job_detail': 'Job Detail',
      'company': 'Company',
      'salary': 'Salary',
      'location': 'Location',
      'job_type': 'Job Type',
      'description': 'Description',
      'requirements': 'Requirements',
      'benefits': 'Benefits',
      'no_internet': 'No internet connection',
      'try_again': 'Try Again',
      'error': 'Error',
      'loading': 'Loading...',
      'search': 'Search',
      'refresh': 'Refresh',
      'mark_as_read': 'Mark as Read',
      'mark_as_unread': 'Mark as Unread',
      'delete_chat': 'Delete Chat',
      'delete_chat_confirm': 'Are you sure you want to delete this chat?',
      'delete_application': 'Delete Application',
      'delete_application_confirm': 'Are you sure you want to delete this application?',
      'pending': 'Pending',
      'reviewing': 'Reviewing',
      'interview': 'Interview',
      'accepted': 'Accepted',
      'rejected': 'Rejected',
      'view_job': 'View Job',
      'upload_resume': 'Upload Resume',
      'update_resume': 'Update Resume',
      'resume_uploaded': 'Resume uploaded',
      'no_resume': 'No resume uploaded yet',
      'feature_coming_soon': 'This feature is coming soon!',
      'all': 'All',
      'completed': 'Completed',
      'role': 'Role',
      'email_required': 'Email is required',
      'email_invalid': 'Invalid email format',
      'password_required': 'Password is required',
      'password_min_length': 'Password must be at least 8 characters',
      'name_required': 'Full name is required',
      'name_min_length': 'Name must be at least 2 characters',
      'confirm_password_required': 'Please confirm your password',
      'passwords_do_not_match': 'Passwords do not match',
      'password_min_length_hint': 'At least 8 characters',
      'demo_info': '💡 For Demo: Use any email and password.',
      'demo_example': 'e.g., test@example.com / 123456',
      'negotiable': 'Negotiable',
      'lao_currency': 'LAK',
      'saved': 'Saved!',
      'weeks_ago': 'weeks ago',
      'months_ago': 'months ago',
      'no_applications_yet': 'No applications yet',
      'no_applications_desc': 'When you apply for jobs, they will appear here.',
      'no_applications_in_category': 'No applications in this category',
      'applied_on': 'Applied on',
      'interview_on': 'Interview on',
      'application_details': 'Application Details',
      'job_title': 'Job Title',
      'status': 'Status',
      'applied_date': 'Applied Date',
      'interview_date': 'Interview Date',
      'cover_letter': 'Cover Letter',
      'application_deleted': 'Application deleted',
      'search_chats_feature': 'Search chats feature',
      'error_loading_chats': 'Error loading chats',
      'start_conversation': 'Send a message to start the conversation',
      'chat_deleted': 'Chat with {name} deleted',
      'error_loading_messages': 'Error loading messages',
      'call_feature': 'Call feature',
      'attach_file': 'Attach file',
      'type_message': 'Type a message...',
      'typing': 'typing...',
      'online': 'Online',
      'offline': 'Offline',
      'chat_info': 'Chat Info',
      'block_user': 'Block User',
      'report': 'Report',
      'report_sent': 'Report sent',
      'loading_partner': 'Loading...',
      'chat_info_message': 'Chat info message',
      'block_user_message': 'Block user message',
      'job_not_found_error': 'Job not found',
      'default_cover_letter': 'Hello, I am very interested in this position and hope to have the opportunity to join your team.',
      'application_submitted': 'Application submitted! Check in \'My Applications\' tab.',
      'job_not_found': 'Job Not Found',
      'job_not_found_message': 'The requested job details could not be found.',
      'job_bookmarked': 'Job bookmarked',
      'job_bookmark_removed': 'Bookmark removed',
      'share_job': 'Share Job',
      'posted_on': 'Posted on',
      'no_description': 'No additional description provided.',
      'about_company': 'About Company',
      'company_description': 'A leading company in the industry with great growth opportunities and benefits.',
      'start_chat_with_hr': 'Start Chat with HR',
      'applying': 'Applying...',
      'clear_all': 'Clear All',
      'select_province': 'Select a province',
      'select_job_type': 'Select job type',
      'salary_range': 'Salary Range',
      'experience_level': 'Experience Level',
      'select_experience': 'Select experience level',
      'sort_by': 'Sort By',
      'apply_filters': 'Apply Filters',
      'no_experience': 'Entry-Level / No Experience',
      'experience_1_2_years': '1-2 Years',
      'experience_3_5_years': '3-5 Years',
      'experience_5_plus_years': '5+ Years',
      'sort_latest': 'Latest',
      'sort_salary_high_low': 'Salary: High-Low',
      'sort_salary_low_high': 'Salary: Low-High',
      'sort_company_az': 'Company A-Z',
      'status_pending': 'Pending',
      'status_reviewing': 'Reviewing',
      'status_interview': 'Interview',
      'status_accepted': 'Accepted',
      'status_rejected': 'Rejected',
      'bookmarks': 'Bookmarks',
      // Bookmark related
      'bookmarked_jobs': 'Bookmarked Jobs',
      'bookmark': 'Bookmark',
      'bookmarked': 'Bookmarked',
      'add_bookmark': 'Add Bookmark',
      'remove_bookmark': 'Remove Bookmark',
      'bookmark_removed': 'Bookmark removed',
      'no_bookmarks': 'No bookmarked jobs yet',
      'no_bookmarks_desc': 'Jobs you save will appear here.',
      'bookmarked_on': 'Bookmarked on',
      'clear_all_bookmarks': 'Clear all bookmarks',
      'clear_all_bookmarks_confirm': 'Are you sure you want to clear all bookmarked jobs?',
      'undo': 'Undo',
      'unknown_job': 'Unknown Job',
      'unknown_company': 'Unknown Company',
      'unknown_location': 'Unknown Location',
      'notifications': 'Notifications',
      'new_notification': 'New Notification',
      'mark_all_read': 'Mark All as Read',
      'clear_notifications': 'Clear All',
      'no_notifications': 'No notifications yet',
      'no_notifications_desc': 'Notifications about your jobs will appear here.',
      'company_profile': 'Company Profile',
      'company_jobs': 'Jobs from this Company',
      'company_reviews': 'Reviews',
      'company_benefits': 'Benefits',
      'company_culture': 'Company Culture',
      'employees_count': 'Employees',
      'founded_year': 'Founded',
      'company_rating': 'Company Rating',
      'write_review': 'Write a Review',
      'read_reviews': 'Read Reviews',
      'reviews': 'Reviews',
      'rating': 'Rating',
      'review_title': 'Review Title',
      'review_content': 'Review Content',
      'pros': 'Pros',
      'cons': 'Cons',
      'current_employee': 'Current Employee',
      'former_employee': 'Former Employee',
      'helpful': 'Helpful',
      'not_helpful': 'Not Helpful',
      'verified_review': 'Verified Review',
      'cv_builder': 'CV Builder',
      'create_cv': 'Create New CV',
      'edit_cv': 'Edit CV',
      'cv_templates': 'CV Templates',
      'personal_information': 'Personal Information',
      'work_experience': 'Work Experience',
      'education': 'Education',
      'projects': 'Projects',
      'certifications': 'Certifications',
      'export_pdf': 'Export to PDF',
      'export_word': 'Export to Word',
      'preview_cv': 'Preview CV',
      'save_cv': 'Save CV',
      'analytics': 'Analytics',
      'dashboard': 'Dashboard',
      'statistics': 'Statistics',
      'profile_views': 'Profile Views',
      'applications_sent': 'Applications Sent',
      'messages_received': 'Messages Received',
      'success_rate': 'Success Rate',
      'job_categories': 'Job Categories',
      'salary_trends': 'Salary Trends',
      'interviews': 'Interviews',
      'schedule_interview': 'Schedule Interview',
      'interview_time': 'Interview Time',
      'interview_type': 'Interview Type',
      'video_call': 'Video Call',
      'phone_call': 'Phone Call',
      'in_person': 'In Person',
      'interview_location': 'Interview Location',
      'meeting_url': 'Meeting URL',
      'interview_notes': 'Notes',
      'interview_preparation': 'Preparation',
      'upcoming_interviews': 'Upcoming Interviews',
      'interview_scheduled': 'Scheduled',
      'interview_confirmed': 'Confirmed',
      'interview_completed': 'Completed',
      'interview_cancelled': 'Cancelled',
      'interview_rescheduled': 'Rescheduled',
      'employer_dashboard': 'Employer Dashboard',
      'welcome': 'Welcome',
      'manage_jobs': 'Manage Jobs',
      'post_and_manage_jobs': 'Post and manage your jobs',
      'manage_applications': 'Manage Applications',
      'review_job_applications': 'Review and manage job applications',
      'update_company_info': 'Update your company information',
      'view_company_insights': 'View insights about your company',
      'post_new_job': 'Post a New Job',
      'my_jobs': 'My Jobs',
      'no_jobs_posted': 'No jobs posted yet',
      'post_your_first_job': 'Post your first job',
      'job_details': 'Job Details',
      'job_title_required': 'Job title is required',
      'job_description': 'Job Description',
      'salary_min': 'Minimum Salary',
      'salary_max': 'Maximum Salary',
      'tags': 'Tags',
      'tags_hint': 'Separate with commas (e.g., developer, full-time)',
      'job_posted_successfully': 'Job posted successfully!',
      'error_posting_job': 'Error posting job',
      'delete_job': 'Delete Job',
      'job_deleted_successfully': 'Job deleted successfully',
      'confirm_delete_job_title': 'Confirm Job Deletion',
      'confirm_delete_job_message': 'Are you sure you want to delete this job?',
      'applicants': 'Applicants',
      'all_applications': 'All Applications',
      'pending_review': 'Pending Review',
      'shortlisted': 'Shortlisted',
      'rejected_applications': 'Rejected',
      'this_week': 'This Week',
      'this_month': 'This Month',
      'no_applications': 'No Applications',
      'no_applications_in_status': 'No applicants in this status yet',
      'years_experience': 'years',
      'view_cv': 'View CV',
      'approve': 'Approve',
      'reject': 'Reject',
      'schedule_interview_action': 'Schedule Interview',
      'send_message': 'Send Message',
      'interviewed': 'Interviewed',
      'unspecified': 'Unspecified',
      'applicant_details': 'Applicant Details',
      'applicant_name': 'Applicant Name',
      'applied_for_position': 'Applied for',
      'experience': 'Experience',
      'open_cv_of': 'Open CV of',
      'download': 'Download',
      'approve_application_title': 'Approve Application',
      'approve_application_confirm': 'Do you want to approve the application of {name}?',
      'application_approved_success': 'Application approved successfully',
      'reject_application_title': 'Reject Application',
      'reject_application_confirm': 'Do you want to reject the application of {name}?',
      'application_rejected_success': 'Application rejected successfully',
      'contact_applicant': 'Contact Applicant',
      'interview_feature_dev': 'Interview scheduling feature is under development',
      'confirm': 'Confirm',
      'company_not_found': 'Company Not Found',
      'company_not_found_message': 'The requested company profile could not be found.',
      'photos': 'Photos',
      'jobs_from_company': 'Jobs from',
      'no_jobs_from_company': 'No jobs from this company yet',
      'check_back_later': 'Please check back later',
      'no_reviews_yet': 'No reviews yet',
      'be_first_to_review': 'Be the first to review this company',
      'no_photos_yet': 'No photos yet',
      'company_photos_here': 'Company photos will be displayed here',
      'contact_info': 'Contact Info',
      'address': 'Address',
      'website': 'Website',
      'x_found_helpful': 'people found this helpful',
      'view_applicants': 'View Applicants',
      'province_required': 'Province is required',
      'job_type_required': 'Job type is required',
      'setup_company_profile': 'Set Up Company Profile',
      'setup_company_subtitle': 'Please complete your company information',
      'company_logo': 'Company Logo',
      'uploading': 'Uploading...',
      'upload_logo': 'Upload Logo',
      'remove_logo': 'Remove Logo',
      'industry_type': 'Industry Type',
      'company_size': 'Company Size',
      'saving': 'Saving...',
      'save_data': 'Save Data',
      'dashboard_overview_subtitle': 'An overview of your dashboard',
      'active_jobs': 'Active Jobs',
      'new_applicants_today': 'New Applicants Today',
      'create_new_job_listing': 'Create a new job listing',
      'edit_your_job_posts': 'Edit your job posts',
      'messages': 'Messages',
      'communicate_with_candidates': 'Communicate with candidates',
      'job_performance': 'Job Performance',
      'total_views': 'Total Views',
      'total_applications': 'Total Applications',
      'conversion_rate': 'Conversion Rate',
      'applicant_stats': 'Applicant Stats',
      'no_jobs_match_filters': 'No jobs match your filter criteria',
      'job_type_full_time': 'Full-time',
      'job_type_part_time': 'Part-time',
      'job_type_contract': 'Contract',
      'job_type_internship': 'Internship',
      'job_type_temporary': 'Temporary',
      'province_attapue': 'Attapeu Province',
      'province_bokeo': 'Bokeo Province',
      'province_bolikhamxai': 'Bolikhamsai Province',
      'province_champasak': 'Champasak Province',
      'province_houaphanh': 'Houaphanh Province',
      'province_khammouane': 'Khammouane Province',
      'province_luang_namtha': 'Luang Namtha Province',
      'province_luang_prabang': 'Luang Prabang Province',
      'province_oudomxay': 'Oudomxay Province',
      'province_phongsaly': 'Phongsaly Province',
      'province_salavan': 'Salavan Province',
      'province_savannakhet': 'Savannakhet Province',
      'province_sainyabuli': 'Sainyabuli Province',
      'province_sekong': 'Sekong Province',
      'province_vientiane': 'Vientiane Province',
      'province_xaisomboun': 'Xaisomboun Province',
      'province_xiangkhouang': 'Xiangkhouang Province',
      'vientiane_capital': 'Vientiane Capital',
      'industry_technology': 'Information Technology',
      'industry_finance': 'Finance',
      'industry_education': 'Education',
      'industry_healthcare': 'Healthcare',
      'industry_commerce': 'Commerce',
      'industry_manufacturing': 'Manufacturing',
      'industry_service': 'Service',
      'industry_other': 'Other',
      'company_size_1_10': '1-10 employees',
      'company_size_11_50': '11-50 employees',
      'company_size_51_200': '51-200 employees',
      'company_size_201_500': '201-500 employees',
      'company_size_501_1000': '501-1000 employees',
      'company_size_1000_plus': '1000+ employees',
      'delete_confirm_message': 'Are you sure you want to delete this?',
      'deleted_successfully': 'Deleted successfully',
      'error_deleting_file': 'Error deleting file',
      'file_uploaded_successfully': 'Successfully uploaded {file}!',
      'error_uploading_file': 'Error uploading file',
      'could_not_open_file': 'Could not open file',
      'file_uploaded': '{file} uploaded',
      'no_file_uploaded': 'No {file} uploaded',
      'view_file': 'View {file}',
      'replace_file': 'Replace',
      'jober_shared_documents': 'Applicant has shared their documents',
      'you_shared_documents': 'You have shared your documents',
      'view_documents': 'View Documents',
      'respond_to_request': 'Respond to Request',
      'waiting_for_jober_response': 'Waiting for applicant\'s response...',
      'verification_request_from': 'Verification Request From',
      'enter_pin_to_share_documents': 'Please enter your 4-digit PIN to authorize',
      'documents_sent_to_employer': 'Documents sent to employer',
      'failed_to_share_documents': 'Failed to share documents',
      'documents_shared_successfully': 'Documents shared successfully',
      'verification_documents': 'Identity Verification Documents',
      'id_card_passport': 'ID Card / Passport',
      'selfie_with_id': 'Selfie with ID',
      'close': 'Close',
      'pin': 'PIN',
      'enter_your_pin': 'Enter your PIN',
      'submit': 'Submit',
      'verification_request_sent_to': 'Verification request sent to',
      'failed_to_send_verification_request': 'Failed to send verification request',
      'view_verification': 'View Verification',
      'identity_verification': 'Identity Verification',
      'id_card_passport': 'ID Card/Passport',
      'selfie_with_id': 'Selfie with ID',
      'upload_id_card': 'Upload ID Card',
      'upload_selfie': 'Upload Selfie',
      'create_or_update_pin': 'Create or Update 4-Digit PIN',
      'leave_empty_to_keep_pin': 'Leave empty to keep current PIN',
      'confirm_new_pin': 'Confirm New PIN',
      'confirm_your_new_pin': 'Confirm your new 4-digit PIN',
      'pin_must_be_4_digits': 'PIN must be 4 digits',
      'pins_do_not_match': 'PINs do not match',
      'status_verified': 'Verified',
      'status_pending': 'Pending Review',
      'status_unverified': 'Unverified',
      'status_label': 'Status'
    },
    // Lao translations
    'lo': {
      'app_title': 'mvp package',
      'splash_title': 'MVP Package',
      'splash_subtitle': 'ແອັບຫາວຽກງານສຳລັບຄົນລາວ',
      'onboarding_title_1': 'ຄົ້ນຫາວຽກງານ',
      'onboarding_desc_1': 'ຊອກຫາວຽກງານທີ່ເໝາະສຳລັບທ່ານ ແລະ ສະໝັກໄດ້ທັນທີ',
      'onboarding_title_2': 'ແຊດກັບນາຍຈ້າງ',
      'onboarding_desc_2': 'ສົນທະນາກັບນາຍຈ້າງໂດຍກົງ ແລະ ຮັບຂໍ້ມູນກ່ຽວກັບບໍລິສັດ',
      'onboarding_title_3': 'ຈັດການໃບສະໝັກ',
      'onboarding_desc_3': 'ຕິດຕາມສະຖານະຂອງໃບສະໝັກງານຂອງທ່ານໄດ້ທຸກເວລາ',
      'skip': 'ຂ້າມ',
      'next': 'ຕໍ່ໄປ',
      'get_started': 'ເລີ່ມຕົ້ນໃຊ້ງານ',
      'login': 'ເຂົ້າສູ່ລະບົບ',
      'welcome_back': 'MVP Jobs',
      'login_to_continue': 'ເຂົ້າສູ່ລະບົບເພື່ອສືບຕໍ່',
      'or_continue_with': 'ຫຼືສືບຕໍ່ດ້ວຍ',
      'email': 'ອີເມວ',
      'password': 'ລະຫັດຜ່ານ',
      'forgot_password': 'ລືມລະຫັດຜ່ານ?',
      'no_account': 'ຍັງບໍ່ມີບັນຊີ? ',
      'register_now': 'ສະໝັກສະມາຊິກ',
      'remember_me': 'ຈື່ຂ້ອຍໄວ້',
      'register': 'ສ້າງບັນຊີ',
      'register_subtitle': 'ເລິ່ມຕ້ອນໃຊ້ງານ mvp package',
      'have_account': 'ມີບັນຊີອີຢູ່ແລ້ວ? ',
      'login_now': 'ເຂົ້າສູ່ລະບົບ',
      'full_name': 'ຊື່-ນາມສະກຸນ',
      'confirm_password': 'ຢືນຢັນລະຫັດຜ່ານ',
      'job_seeker': 'ຜູ້ຫາວຽກງານ',
      'employer': 'ນາຍຈ້າງ',
      'jobs': 'ຫາວຽກງານ',
      'applied': 'ສະໝັກແລ້ວ',
      'chat': 'ແຊດ',
      'profile': 'ໂປຣໄຟລ໌',
      'post_job': 'ປະກາດງານ',
      'all_jobs': 'ງານທັ້ງໝົດ',
      'search_jobs': 'ຄົ້ນຫາວຽກງານ...',
      'filter': 'ກັອງ',
      'no_jobs_found': 'ບໍ່ພົບງານທີ່ຄ້ອນຫາ',
      'my_applications': 'ໃບສະໝັກຂອງຂ້ອຍ',
      'logout': 'ອອກຈາກລະບົບ',
      'logout_confirm': 'ທ່ານຕ້ອງການອອກຈາກລະບົບບໍ?',
      'cancel': 'ຍົກເລີກ',
      'ok': 'ຕົກລົງ',
      'edit_profile': 'ແກ້ໄຂໂປຣໄຟລ໌',
      'tap_to_change_profile_picture': 'ແຕະເພື່ອປ່ຽນຮູບໂປຣໄຟລ໌',
      'personal_info': 'ຂໍ້ມູນສ່ວນຕົວ',
      'phone': 'ເບີໂທລະສັບ',
      'province': 'ແຂວງ/ເມືອງ',
      'skills': 'ທັກສະ ແລະ ຄວາມສາມາດ',
      'about': 'ກ່ຽວກັບຕົນເອງ',
      'introduce_yourself': 'ແນະນຳຕົນເອງ',
      'select_skills': 'ເລືອກທັກສະຂອງທ່ານ',
      'documents': 'ເອກະສານ ແລະ ເລຊູເມ',
      'no_chats': 'ຍັງບໍ່ມີການສົນທະນາ',
      'no_chats_desc': 'ເມື່ອທ່ານສະໝັກງານ ການສົນທະນາຈະປາກົດທີ່ນີ້',
      'find_jobs': 'ຫາວຽກງານທີ່ສົນໃຈ',
      'today': 'ມື້ນີ້',
      'yesterday': 'ມື້ວານ',
      'days_ago': 'ມື້ທີ່ແລ້ວ',
      'save': 'ບັນທຶກ',
      'delete': 'ລົບ',
      'apply': 'ສະໝັກ',
      'applied_success': 'ສະໝັກງານສຳເລັດ',
      'apply_job': 'ສະໝັກງານນີ້',
      'job_detail': 'ລາຍລະອຽດງານ',
      'company': 'ບໍລິສັດ',
      'salary': 'ເງິນເດືອນ',
      'location': 'ສະຖານທີ່',
      'job_type': 'ປະເພດງານ',
      'description': 'ລາຍລະອຽດ',
      'requirements': 'ຄວາມຕ້ອງການ',
      'benefits': 'ສິດຜົນ',
      'no_internet': 'ບໍ່ມີການເຊື່ອມຕໍ່ອິນເຕີເນັດ',
      'try_again': 'ລອງອີກຄັ້ງ',
      'error': 'ເກີດຂໍ້ຜິດພາດ',
      'loading': 'ກຳລັງໂຫຼດ...',
      'search': 'ຄົ້ນຫາ',
      'refresh': 'ຣີເຟຣດ',
      'mark_as_read': 'ທໍໂຄ່ງໜາຍວ່າອ່ານແລ້ວ',
      'mark_as_unread': 'ທໍໂຄ່ງໜາຍວ່າຍັງບໍ່ອ່ານ',
      'delete_chat': 'ລົບແຊດ',
      'delete_chat_confirm': 'ທ່ານຕ້ອງການລົບແຊດນີ້ບໍ?',
      'delete_application': 'ລົບໃບສະໝັກ',
      'delete_application_confirm': 'ທ່ານຕ້ອງການລົບໃບສະໝັກນີ້ບໍ?',
      'pending': 'ລໍຖ້າການພິຈາລະນາ',
      'reviewing': 'ກຳລັງພິຈາລະນາ',
      'interview': 'ການສັມພາດ',
      'accepted': 'ໄດ້ຮັບການຢອມຮັບ',
      'rejected': 'ຖືກປະຕິເສດ',
      'view_job': 'ດູງານ',
      'upload_resume': 'ອັບໂຫລດເລຊູເມ',
      'update_resume': 'ອັບເດດເລຊູເມ',
      'resume_uploaded': 'ມີໄຟລ໌ເລຊູເມແລ້ວ',
      'no_resume': 'ຍັງບໍ່ໄດ້ອັບໂຫລດເລຊູເມ',
      'feature_coming_soon': 'ຟີເຈີນີ້ກຳລັງຈະເປີດໃຫ້ໃຊ້ງານໃນໄວໆນີ້!',
      'all': 'ທັງໝົດ',
      'completed': 'ສຳເລັດ',
      'role': 'ບົດບາດ',
      'email_required': 'ກະລຸນາປ້ອນອີເມວ',
      'email_invalid': 'ຮູບແບບອີເມວບໍ່ຖືກຕ້ອງ',
      'password_required': 'ກະລຸນາປ້ອນລະຫັດຜ່ານ',
      'password_min_length': 'ລະຫັດຜ່ານຕ້ອງມີຢ່າງໜ້ອຍ 8 ໂຕອັກສອນ',
      'name_required': 'ກະລຸນາກໍລອກຊື່-ນາມສະກຸນ',
      'name_min_length': 'ຊື່ຕ້ອງມີຢ່າງໜ້ອຍ 2 ໂຕອັກສອນ',
      'confirm_password_required': 'ກະລຸນາຢືນຍັນລະຫັດຜ່ານ',
      'passwords_do_not_match': 'ລະຫັດຜ່ານບໍ່ຕົງກັນ',
      'password_min_length_hint': 'ຢ່າງໜ້ອຍ 8 ໂຕອັກສອນ',
      'demo_info': '💡 ສຳລັບທົດສອບ: ໃຊ້ອີເມວແລະລະຫັດຜ່ານໃດກໍ່ໄດ້',
      'demo_example': 'ຕົວຢ່າງ: test@example.com / 123456',
      'negotiable': 'ຕາມຕົກລົງ',
      'lao_currency': 'ລາວ',
      'saved': 'ບັນທຶກແລ້ວ!',
      'weeks_ago': 'ອາທິດທີ່ແລ້ວ',
      'months_ago': 'ເດືອນທີ່ແລ້ວ',
      'no_applications_yet': 'ຍັງບໍ່ມີໃບສະໝັກງານ',
      'no_applications_desc': 'ເມື່ອທ່ານສະໝັກງານ ໃບສະໝັກຈະປາກົດທີ່ນີ້',
      'no_applications_in_category': 'ບໍ່ມີໃບສະໝັກໃນໝວດນີ້',
      'applied_on': 'ສະໝັກເມື່ອ',
      'interview_on': 'ສັມພາດເມື່ອ',
      'application_details': 'ລາຍລະອຽດໃບສະໝັກ',
      'job_title': 'ຕໍາແໜ່ງງານ',
      'status': 'ສະຖານະ',
      'applied_date': 'ວັນທີສະໝັກ',
      'interview_date': 'ວັນທີສັມພາດ',
      'cover_letter': 'ຈົດໝາຍສະໝັກງານ',
      'application_deleted': 'ລົບໃບສະໝັກແລ້ວ',
      'search_chats_feature': 'ຄົ້ນຫາແຊດ',
      'error_loading_chats': 'ບໍ່ສາມາດໂຫຼດແຊດໄດ້',
      'start_conversation': 'ສົ່ງຂໍ້ຄວາມເພື່ອເລີ່ມການສົນທນາ',
      'chat_deleted': 'ລົບແຊດກັບ',
      'error_loading_messages': 'ບໍ່ສາມາດໂຫຼດຂໍ້ຄວາມໄດ້',
      'call_feature': 'ໂທລະສັບ',
      'attach_file': 'ແນບໄຟລ໌',
      'type_message': 'ພິມຂໍ້ຄວາມ...',
      'typing': 'ກຳລັງພິມ...',
      'online': 'ອອນໄລນ໌',
      'offline': 'ອອບໄລນ໌',
      'chat_info': 'ຂໍ້ມູນແຊດ',
      'block_user': 'ບລັອກຜູ້ໃຊ້',
      'report': 'ລາຍງານ',
      'report_sent': 'ລາຍງານຖືກສົ່ງແລ້ວ',
      'loading_partner': 'ກຳລັງໂຫຼດ...',
      'chat_info_message': 'ຂໍ້ມູນແຊດ',
      'block_user_message': 'ບລັອກຜູ້ໃຊ້',
      'job_not_found_error': 'ບໍ່ພົບຂໍ້ມູນງານ',
      'default_cover_letter': 'ສະບາຍດີເຈົ້າ ຂ້ອຍສົນໃຈຕໍາແໜ່ງງານນີ້ຫຼາຍ ແລະ ມີຄວາມຫວັງວ່າຈະໄດ້ມີໂອກາດຮ່ວມງານກັບທີມຂອງທ່ານ',
      'application_submitted': 'ສົ່ງໃບສະໝັກແລ້ວ! ກວດສອບໃນແຖບໃບສະໝັກຂອງຂ້ອຍ',
      'job_not_found': 'ບໍ່ພົບງານ',
      'job_not_found_message': 'ບໍ່ພົບລາຍລະອຽດງານທີ່ຕ້ອງການ',
      'job_bookmarked': 'ບັນທຶກງານແລ້ວ',
      'job_bookmark_removed': 'ຍົກເລີກການບັນທຶກ',
      'share_job': 'ແບ່ງປັນງານ',
      'posted_on': 'ປະກາດເມື່ອ',
      'no_description': 'ບໍ່ມີລາຍລະອຽດເພີ່ມເຕີມ',
      'about_company': 'ກ່ຽວກັບບໍລິສັດ',
      'company_description': 'ບໍລິສັດຊັ້ນນໍາໃນອຸດສາຫະກໍາ ພ້ອມໂອກາດເຕີບໂຕ ແລະ ສະວັດດິການທີ່ດີ',
      'start_chat_with_hr': 'ເລີ່ມການສົນທະນາກັບ HR',
      'applying': 'ກຳລັງສົ່ງ...',
      'clear_all': 'ລົບລ້າງທັງໝົດ',
      'select_province': 'ເລືອກແຂວງ/ເມືອງ',
      'select_job_type': 'ເລືອກປະເພດງານ',
      'salary_range': 'ຊ່ວງເງິນເດືອນ',
      'experience_level': 'ລະດັບປະສົບການ',
      'select_experience': 'ເລືອກລະດັບປະສົບການ',
      'sort_by': 'ຈັດລຽງຕາມ',
      'apply_filters': 'ນຳໃຊ້ຕົວກອງ',
      'no_experience': 'ໃໝ່/ບໍ່ມີປະສົບການ',
      'experience_1_2_years': '1-2 ປີ',
      'experience_3_5_years': '3-5 ປີ',
      'experience_5_plus_years': '5+ ປີ',
      'sort_latest': 'ຫຼ້າສຸດ',
      'sort_salary_high_low': 'ເງິນເດືອນ: ສູງ-ຕ່ຳ',
      'sort_salary_low_high': 'ເງິນເດືອນ: ຕ່ຳ-ສູງ',
      'sort_company_az': 'ບໍລິສັດ A-Z',
      'status_pending': 'ລໍຖ້າການພິຈາລະນາ',
      'status_reviewing': 'ກຳລັງພິຈາລະນາ',
      'status_interview': 'ນັດສັມພາດ',
      'status_accepted': 'ໄດ້ຮັບການຄັດເລືອກ',
      'status_rejected': 'ບໍ່ໄດ້ຮັບການຄັດເລືອກ',
      'bookmarks': 'ບຸກມາກ',
      // Bookmark related
      'bookmarked_jobs': 'ງານທີ່ບັນທຶກໄວ້',
      'bookmark': 'ບັນທຶກ',
      'bookmarked': 'ບັນທຶກແລ້ວ',
      'add_bookmark': 'ບັນທຶກງານ',
      'remove_bookmark': 'ຍົກເລີກບັນທຶກ',
      'bookmark_removed': 'ຍົກເລີກການບັນທຶກແລ້ວ',
      'job_bookmarked': 'ບັນທຶກງານແລ້ວ',
      'no_bookmarks': 'ຍັງບໍ່ມີງານທີ່ບັນທຶກ',
      'no_bookmarks_desc': 'ງານທີ່ທ່ານບັນທຶກໄວ້ຈະປາກົດທີ່ນີ້',
      'bookmarked_on': 'ບັນທຶກເມື່ອ',
      'clear_all_bookmarks': 'ລົບງານທີ່ບັນທຶກທັງໝົດ',
      'clear_all_bookmarks_confirm': 'ທ່ານແນ່ໃຈບໍ່ວ່າຕ້ອງການລົບງານທີ່ບັນທຶກທັງໝົດ?',
      'undo': 'ຍົກເລີກ',
      'unknown_job': 'ບໍ່ທຮາບຕຳແໜ່ງ',
      'unknown_company': 'ບໍ່ທຮາບບໍລິສັດ',
      'unknown_location': 'ບໍ່ທຮາບສະຖານທີ່',
      // Notification related
      'notifications': 'ການແຈ້ງເຕືອນ',
      'new_notification': 'ການແຈ້ງເຕືອນໃໝ່',
      'mark_all_read': 'ທໍໂຄ່ງທັງໝົດວ່າອ່ານແລ້ວ',
      'clear_notifications': 'ລົບທັງໝົດ',
      'no_notifications': 'ບໍ່ມີການແຈ້ງເຕືອນ',
      'no_notifications_desc': 'ການແຈ້ງເຕືອນກ່ຽວກັບງານຈະປາກົດທີ່ນີ້',
      // Company related
      'company_profile': 'ໂປຣໄຟລ໌ບໍລິສັດ',
      'company_jobs': 'ງານຂອງບໍລິສັດນີ້',
      'company_reviews': 'ບົດຄິດເຫັນ',
      'company_benefits': 'ສິດຜົນ',
      'company_culture': 'ວັດທະນະທໍາບໍລິສັດ',
      'employees_count': 'ຈໍານວນພະນັກງານ',
      'founded_year': 'ປີທີ່ກໍ່ຕັ້ງ',
      'company_rating': 'ຄະແນນບໍລິສັດ',
      'write_review': 'ຂຽນບົດຄິດເຫັນ',
      'read_reviews': 'ອ່ານບົດຄິດເຫັນ',
      // Review related
      'reviews': 'ບົດຄິດເຫັນ',
      'rating': 'ຄະແນນ',
      'review_title': 'ຫົວຂໍ້ບົດຄິດເຫັນ',
      'review_content': 'ເນື້ອໃນບົດຄິດເຫັນ',
      'pros': 'ຈຸດດີ',
      'cons': 'ຈຸດທີ່ຄວນປັບປຸງ',
      'current_employee': 'ພະນັກງານປັດຈຸບັນ',
      'former_employee': 'ອະດີດພະນັກງານ',
      'helpful': 'ມີປະໂຫຍດ',
      'not_helpful': 'ບໍ່ມີປະໂຫຍດ',
      'verified_review': 'ບົດຄິດເຫັນທີ່ຢືນຢັນແລ້ວ',
      // CV Builder related
      'cv_builder': 'ສ້າງ CV',
      'create_cv': 'ສ້າງ CV ໃໝ່',
      'edit_cv': 'ແກ້ໄຂ CV',
      'cv_templates': 'ແບບຟອມ CV',
      'personal_information': 'ຂໍ້ມູນສ່ວນຕົວ',
      'work_experience': 'ປະສົບການການງານ',
      'education': 'ການສຶກສາ',
      'projects': 'ໂປຣເຈັກ',
      'certifications': 'ໃບຢັ້ງຢືນ',
      'export_pdf': 'ສົ່ງອອກ PDF',
      'export_word': 'ສົ່ງອອກ Word',
      'preview_cv': 'ເບິ່ງຕົວຢ່າງ CV',
      'save_cv': 'ບັນທຶກ CV',
      // Analytics related
      'analytics': 'ສະຖິຕິ',
      'dashboard': 'ແດສບອດ',
      'statistics': 'ສະຖິຕິ',
      'profile_views': 'ການເບິ່ງໂປຣໄຟລ໌',
      'applications_sent': 'ໃບສະໝັກທີ່ສົ່ງ',
      'messages_received': 'ຂໍ້ຄວາມທີ່ໄດ້ຮັບ',
      'success_rate': 'ອັດຕາຄວາມສຳເລັດ',
      'job_categories': 'ປະເພດງານ',
      'salary_trends': 'ແນວໂນ້ມເງິນເດືອນ',
      // Interview related
      'interviews': 'ການສັມພາດ',
      'schedule_interview': 'ນັດເວລາສັມພາດ',
      'interview_time': 'ເວລາສັມພາດ',
      'interview_type': 'ປະເພດການສັມພາດ',
      'video_call': 'ວິດິໂອໂທ',
      'phone_call': 'ໂທລະສັບ',
      'in_person': 'ພົບໜ້າ',
      'interview_location': 'ສະຖານທີ່ສັມພາດ',
      'meeting_url': 'ລິ້ງການປະຊຸມ',
      'interview_notes': 'ບັນທຶກ',
      'interview_preparation': 'ການກະກຽມ',
      'upcoming_interviews': 'ການສັມພາດທີ່ຈະມາເຖິງ',
      'interview_scheduled': 'ນັດແລ້ວ',
      'interview_confirmed': 'ຢືນຢັນແລ້ວ',
      'interview_completed': 'ສຳເລັດແລ້ວ',
      'interview_cancelled': 'ຍົກເລີກແລ້ວ',
      'interview_rescheduled': 'ເລື່ອນເວລາແລ້ວ',
      // Employer dashboard translations
      'employer_dashboard': 'ແດຊ໌ບອດນາຍຈ້າງ',
      'welcome': 'ຍິນດີຕ້ອນຮັບ',
      'manage_jobs': 'ຈັດການວຽກ',
      'post_and_manage_jobs': 'ປະກາດ ແລະ ຈັດການວຽກຂອງທ່ານ',
      'manage_applications': 'ຈັດການໃບສະໝັກ',
      'review_job_applications': 'ກວດສອບ ແລະ ຈັດການໃບສະໝັກວຽກ',
      'update_company_info': 'ອັບເດດຂໍ້ມູນບໍລິສັດຂອງທ່ານ',
      'view_company_insights': 'ເບິ່ງຂໍ້ມູນเชิงເລິກຂອງບໍລິສັດ',
      'post_new_job': 'ປະກາດວຽກໃໝ່',
      'my_jobs': 'ວຽກຂອງຂ້ອຍ',
      'no_jobs_posted': 'ຍັງບໍ່ມີວຽກທີ່ປະກາດ',
      'post_your_first_job': 'ປະກາດວຽກທຳອິດຂອງທ່ານ',
      'job_details': 'ລາຍລະອຽດວຽກງານ',
      'job_title_required': 'ກະລຸນາປ້ອນຕຳແໜ່ງງານ',
      'job_description': 'ລາຍລະອຽດວຽກງານ',
      'salary_min': 'ເງິນເດືອນຂັ້ນຕ່ຳ',
      'salary_max': 'ເງິນເດືອນສູງສຸດ',
      'tags': 'ແທັກ',
      'tags_hint': 'ແຍກດ້ວຍເຄື່ອງໝາຍຈຸດ (ຕົວຢ່າງ: developer, full-time)',
      'job_posted_successfully': 'ປະກາດວຽກສຳເລັດແລ້ວ!',
      'error_posting_job': 'ເກີດຂໍ້ຜິດພາດໃນການປະກາດວຽກ',
      'delete_job': 'ລົບວຽກ',
      'job_deleted_successfully': 'ລົບວຽກສຳເລັດແລ້ວ',
      'confirm_delete_job_title': 'ຢືນຢັນການລົບວຽກ',
      'confirm_delete_job_message': 'ທ່ານແນ່ໃຈບໍ່ວ່າຕ້ອງການລົບວຽກນີ້?',

      // Employer Applications Page
      'applicants': 'ຜູ້ສະໝັກວຽກ',
      'all_applications': 'ໃບສະໝັກທັງໝົດ',
      'pending_review': 'ລໍຖ້າພິຈາລະນາ',
      'shortlisted': 'ຜ່ານເຂົ້າຮອບ',
      'rejected_applications': 'ບໍ່ຜ່ານ',
      'this_week': 'ອາທິດນີ້',
      'this_month': 'ເດືອນນີ້',
      'no_applications': 'ບໍ່ມີໃບສະໝັກ',
      'no_applications_in_status': 'ຍັງບໍ່ມີຜູ້ສະໝັກໃນສະຖານະນີ້',
      'years_experience': 'ປີ',
      'view_cv': 'ເບິ່ງ CV',
      'approve': 'ອະນຸມັດ',
      'reject': 'ບໍ່ອະນຸມັດ',
      'schedule_interview_action': 'ນັດສຳພາດ',
      'send_message': 'ສົ່ງຂໍ້ຄວາມ',
      'interviewed': 'ສຳພາດແລ້ວ',
      'unspecified': 'ບໍ່ລະບຸ',
      'applicant_details': 'ລາຍລະອຽດຜູ້ສະໝັກ',
      'applicant_name': 'ຊື່ ແລະ ນາມສະກຸນ',
      'applied_for_position': 'ຕຳແໜ່ງທີ່ສະໝັກ',
      'experience': 'ປະສົບການ',
      'open_cv_of': 'ເປີດ CV ຂອງ',
      'download': 'ດາວໂຫຼດ',
      'approve_application_title': 'ອະນຸມັດໃບສະໝັກ',
      'approve_application_confirm': 'ທ່ານຕ້ອງການອະນຸມັດໃບສະໝັກຂອງ {name} ບໍ່?',
      'application_approved_success': 'ອະນຸມັດໃບສະໝັກສຳເລັດແລ້ວ',
      'reject_application_title': 'ບໍ່ອະນຸມັດໃບສະໝັກ',
      'reject_application_confirm': 'ທ່ານຕ້ອງການບໍ່ອະນຸມັດໃບສະໝັກຂອງ {name} ບໍ່?',
      'application_rejected_success': 'ບໍ່ອະນຸມັດໃບສະໝັກສຳເລັດແລ້ວ',
      'contact_applicant': 'ເລີ່ມສົນທະນາ',
      'interview_feature_dev': 'ຟີເຈີຈັດຕາຕະລາງສຳພາດກຳລັງພັດທະນາ',
      'confirm': 'ຢືນຢັນ',

      // Verification Flow
      'jober_shared_documents': 'ຜູ້ສະໝັກໄດ້ແບ່ງປັນເອກະສານແລ້ວ',
      'you_shared_documents': 'ທ່ານໄດ້ແບ່ງປັນເອກະສານຂອງທ່ານ',
      'view_documents': 'ເບິ່ງເອກະສານ',
      'respond_to_request': 'ຕອບກັບຄຳຮ້ອງຂໍ',
      'waiting_for_jober_response': 'ກຳລັງລໍຖ້າການຕອບກັບຈາກຜູ້ສະໝັກ...',
      'verification_request_from': 'ຄຳຮ້ອງຂໍເອກະສານຢືນຢັນຈາກ',
      'enter_pin_to_share_documents': 'ກະລຸນາໃສ່ລະຫັດ PIN 4 ຕົວຂອງທ່ານເພື່ອອະນຸຍາດ',
      'documents_sent_to_employer': 'ສົ່ງເອກະສານໃຫ້ກັບນາຍຈ້າງແລ້ວ',
      'failed_to_share_documents': 'ການແບ່ງປັນເອກະສານລົ້ມເຫລວ',
      'documents_shared_successfully': 'ແບ່ງປັນເອກະສານສຳເລັດ',
      'verification_documents': 'ເອກະສານຢືນຢັນຕົວຕົນ',
      'id_card_passport': 'ບັດປະຈຳຕົວ / ໜັງສືຜ່ານແດນ',
      'selfie_with_id': 'ຮູບຖ່າຍຄູ່ກັບບັດ',
      'close': 'ປິດ',
      'pin': 'ລະຫັດ PIN',
      'enter_your_pin': 'ໃສ່ລະຫັດ PIN ຂອງທ່ານ',
      'submit': 'ຢືນຢັນ',
      'verification_request_sent_to': 'ສົ່ງຄຳຮ້ອງຂໍການຢືນຢັນໄປທີ່',
      'failed_to_send_verification_request': 'ການສົ່ງຄຳຮ້ອງຂໍການຢືນຢັນລົ້ມເຫລວ',
      'view_verification': 'ເບິ່ງການຢືນຢັນ',
      'identity_verification': 'ການຢືນຢັນຕົວຕົນ',
      'id_card_passport': 'ບັດປະຈຳຕົວ / ໜັງສືຜ່ານແດນ',
      'selfie_with_id': 'ຮູບຖ່າຍຄູ່ກັບບັດ',
      'upload_id_card': 'ອັບໂຫຼດບັດປະຈຳຕົວ',
      'upload_selfie': 'ອັບໂຫຼດຮູບຖ່າຍຄູ່ກັບບັດ',
      'create_or_update_pin': 'ສ້າງ ຫຼື ອັບເດດ PIN 4 ຕົວ',
      'leave_empty_to_keep_pin': 'ປະໄວ້ຫວ່າງເພື່ອຮັກສາ PIN ປັດຈຸບັນ',
      'confirm_new_pin': 'ຢືນຢັນ PIN ໃໝ່',
      'confirm_your_new_pin': 'ຢືນຢັນ PIN 4 ຕົວໃໝ່ຂອງທ່ານ',
      'pin_must_be_4_digits': 'PIN ຕ້ອງເປັນ 4 ຕົວເລກ',
      'pins_do_not_match': 'ລະຫັດ PIN ບໍ່ກົງກັນ',
      'status_verified': 'ຢືນຢັນແລ້ວ',
      'status_pending': 'ກຳລັງລໍຖ້າກວດສອບ',
      'status_unverified': 'ຍັງບໍ່ໄດ້ຢືນຢັນ',
      'status_label': 'ສະຖານະ',

      // Company Profile Page
      'company_not_found': 'ບໍ່ພົບບໍລິສັດ',
      'company_not_found_message': 'ບໍ່ພົບຂໍ້ມູນບໍລິສັດທີ່ທ່ານຕ້ອງການ',
      'photos': 'ຮູບພາບ',
      'jobs_from_company': 'ວຽກຈາກ',
      'no_jobs_from_company': 'ຍັງບໍ່ມີວຽກຈາກບໍລິສັດນີ້',
      'check_back_later': 'ກະລຸນາກັບມາເບິ່ງໃໝ່ภายหลัง',
      'no_reviews_yet': 'ຍັງບໍ່ມີรีวิว',
      'be_first_to_review': 'ເປັນຄົນທຳອິດທີ່รีวิวບໍລິສັດນີ້',
      'no_photos_yet': 'ຍັງບໍ່ມີຮູບພາບ',
      'company_photos_here': 'ຮູບພາບຂອງບໍລິສັດຈະສະແດງຢູ່ນີ້',
      'contact_info': 'ຂໍ້ມູນຕິດຕໍ່',
      'address': 'ທີ່ຢູ່',
      'website': 'ເວັບໄຊ',
      'x_found_helpful': 'ຄົນເຫັນວ່າມີປະໂຫຍດ',
      'view_applicants': 'ເບິ່ງຜູ້ສະໝັກ',
      'province_required': 'ກະລຸນາເລືອກແຂວງ',
      'job_type_required': 'ກະລຸນາເລືອກປະເພດງານ',

      // Setup Company Page
      'setup_company_profile': 'ຕັ້ງຄ່າໂປຣໄຟລ໌ບໍລິສັດ',
      'setup_company_subtitle': 'ກະລຸນາໃສ່ຂໍ້ມູນບໍລິສັດຂອງທ່ານໃຫ້ຄົບຖ້ວນ',
      'company_logo': 'ໂລໂກ້ບໍລິສັດ',
      'uploading': 'ກຳລັງອັບໂຫລດ...',
      'upload_logo': 'ອັບໂຫລດໂລໂກ້',
      'remove_logo': 'ລົບໂລໂກ້',
      'industry_type': 'ປະເພດອຸດສາຫະກໍາ',
      'company_size': 'ຂະໜາດບໍລິສັດ',
      'saving': 'ກຳລັງບັນທຶກ...',
      'save_data': 'ບັນທຶກຂໍ້ມູນ',

      // Dashboard & Analytics
      'dashboard_overview_subtitle': 'ພາບລວມໜ້າແດຊ໌ບອດຂອງທ່ານ',
      'active_jobs': 'ວຽກທີ່ເປີດຮັບ',
      'new_applicants_today': 'ຜູ້ສະໝັກໃໝ່ມື້ນີ້',
      'create_new_job_listing': 'ສ້າງປະກາດວຽກໃໝ່',
      'edit_your_job_posts': 'ແກ້ໄຂປະກາດວຽກຂອງທ່ານ',
      'messages': 'ຂໍ້ຄວາມ',
      'communicate_with_candidates': 'ສົນທະນາກັບຜູ້ສະໝັກ',
      'job_performance': 'ປະສິດທິພາບຂອງວຽກ',
      'total_views': 'ຍອດເບິ່ງທັງໝົດ',
      'total_applications': 'ຍອດສະໝັກທັງໝົດ',
      'conversion_rate': 'ອັດຕາການສະໝັກ',
      'applicant_stats': 'ສະຖິຕິຜູ້ສະໝັກ',
      'no_jobs_match_filters': 'ບໍ່ພົບວຽກທີ່ກົງກັບເງື່ອນໄຂການກັ່ນຕອງຂອງທ່ານ',

      // Job Types
      'job_type_full_time': 'ເຕັມເວລາ',
      'job_type_part_time': 'ບໍ່ເຕັມເວລາ',
      'job_type_contract': 'ສັນຍາຈ້າງ',
      'job_type_internship': 'ຝຶກງານ',
      'job_type_temporary': 'ຊົ່ວຄາວ',

      // Provinces
      'province_attapue': 'ແຂວງອັດຕະປື',
      'province_bokeo': 'ແຂວງບໍ່ແກ້ວ',
      'province_bolikhamxai': 'ແຂວງບໍລິຄຳໄຊ',
      'province_champasak': 'ແຂວງຈຳປາສັກ',
      'province_houaphanh': 'ແຂວງຫົວພັນ',
      'province_khammouane': 'ແຂວງຄຳມ່ວນ',
      'province_luang_namtha': 'ແຂວງຫຼວງນໍ້າທາ',
      'province_luang_prabang': 'ແຂວງຫຼວງພະບາງ',
      'province_oudomxay': 'ແຂວງອຸດົມໄຊ',
      'province_phongsaly': 'ແຂວງຜົ້ງສາລີ',
      'province_salavan': 'ແຂວງສາລະວັນ',
      'province_savannakhet': 'ແຂວງສະຫວັນນະເຂດ',
      'province_sainyabuli': 'ແຂວງໄຊຍະບູລີ',
      'province_sekong': 'ແຂວງເຊກອງ',
      'province_vientiane': 'ແຂວງວຽງຈັນ',
      'province_xaisomboun': 'ແຂວງໄຊສົມບູນ',
      'province_xiangkhouang': 'ແຂວງຊຽງຂວາງ',
      'vientiane_capital': 'ນະຄອນຫຼວງວຽງຈັນ',

      // Industries
      'industry_technology': 'ເທກໂນໂລຢີສາລະສະໜ່ອງ',
      'industry_finance': 'ການເງິນ',
      'industry_education': 'ການສຶກສາ',
      'industry_healthcare': 'ສາທາລະນະສຸກ',
      'industry_commerce': 'ການຄ້າ',
      'industry_manufacturing': 'ອຸດສາຫະກໍາ',
      'industry_service': 'ບໍລິການ',
      'industry_other': 'ອື່ນໆ',

      // Company Sizes
      'company_size_1_10': '1-10 ຄົນ',
      'company_size_11_50': '11-50 ຄົນ',
      'company_size_51_200': '51-200 ຄົນ',
      'company_size_201_500': '201-500 ຄົນ',
      'company_size_501_1000': '501-1000 ຄົນ',
      'company_size_1000_plus': '1000+ ຄົນ',
      'delete_confirm_message': 'ທ່ານຕ້ອງການລົບແທ້ໆບໍ?',
      'deleted_successfully': 'ລົບສຳເລັດແລ້ວ',
      'error_deleting_file': 'ເກີດຂໍ້ຜິດພາດໃນການລົບໄຟລ໌',
      'file_uploaded_successfully': 'ອັບໂຫຼດ {file} ສຳເລັດແລ້ວ!',
      'error_uploading_file': 'ເກີດຂໍ້ຜິດພາດໃນການອັບໂຫຼດໄຟລ໌',
      'could_not_open_file': 'ບໍ່ສາມາດເປີດໄຟລ໌ໄດ້',
      'file_uploaded': 'ມີ {file} ແລ້ວ',
      'no_file_uploaded': 'ຍັງບໍ່ໄດ້ອັບໂຫຼດ {file}',
      'view_file': 'ເບິ່ງ {file}',
      'replace_file': 'ປ່ຽນໄຟລ໌',
    }
  };

  static String translate(String key, String languageCode) {
    final translations = _localizedStrings[languageCode];
    if (translations == null) return key;
    return translations[key] ?? key;
  }

  static String of(BuildContext context, String key) {
    // In a real implementation, we would get the language code from the context
    // For now, we'll default to Lao
    return translate(key, 'lo');
  }
}
